
SELECT DEPARTMENTS
FROM EMPLOYEES
WHERE DEPARTMENT_ID BETWEEN 50 AND 120;

SELECT*
FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN '2002/02/02' AND '2003/12/05';

SELECT*
FROM EMPLOYEES
WHERE LAST_NAME IN ('LORENTZ','CHEN');

SELECT *
FROM job_history
ORDER BY 2 desc;

select*
from EMPLOYEES
where LAST_NAME not like '%ki%'
order by last_name desc;

select*
from departments
where manager_id is null;

select*
from EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL;



UPDATE REGIONS
SET REGION_NAME='EUROPA'
WHERE REGION_ID=1;
SELECT*
FROM REGIONS


DELETE from COUNTRIES
WHERE COUNTRY_ID IN ('ZW','ZM','KW','PW');

SELECT * FROM  COUNTRIES;


DELETE FROM EMPLOYESS
WHERE PHONE_NUMBER LIKE '515%' AND FIRST_NAME LIKE 'D%';

CREATE TABLE WOJEWODZTWA (
id_wojewodztwa int,
nazwa_wojewodztwa varchar (30),
stolica_wojewodztwa varchar(30),
powierzchnia number (38),
zabytki varchar (300)
);

select*
from wojewodztwa



CREATE TABLE MIASTO (
id_ulicy int NOT NULL,
nazwa_ulicy varchar (30) NOT NULL,
liczba_domow varchar(30) NOT NULL,
powierzchnia number (38) NOT NULL,
zabytki varchar (300) NOT NULL,
CONSTRAINT PK_MIASTO PRIMARY KEY (ID_ULICY)
);

SELECT*
FROM MIASTO;

DROP TABLE MIASTO;


ALTER TABLE  MIASTO
ADD (wojewodztwa varchar (30), kraje varchar (30));

ALTER TABLE MIASTO
MODIFY wojewodztwa null

ALTER TABLE MIASTO
MODIFY kraje not null;


ALTER TABLE MIASTO DROP (WOJEWODZTA, KRAJE);



CONSTRAINT PK_MIASTO PRIMARY KEY (ID_ULICY

alter table miasto
ADD CONSTRAINT pk_miasto
FOREIGN KEY (kraje_id) REFERENCES countries(country_id);

alter table MIASTO
ADD COUNTRY1 CHAR (2 BYTE) NULL;

ALTER TABLE MIASTO MODIFY NAZWA_ULICY CHAR (2);

alter table MIASTO
ADD CONSTRAINT FK_COUNTRYMIASTO
FOREIGN KEY (COUNTRY1) REFERENCES countries(country_id);




SELECT*
FROM MIASTO;


SELECT FIRST_NAME, LAST_NAME, MAX (HIRE_DATE)
FROM EMPLOYEES
GROUP BY FIRST_NAME, LAST_NAME
ORDER BY FIRST_NAME,LAST_NAME DESC;


SELECT *
FROM employees
WHERE HIRE_DATE = (SELECT MAX(HIRE_DATE)
                FROM employees
                WHERE ROWNUM <= 1
               );

SELECT MAX(HIRE_DATE) AS OSTANI_ZATRUDNIONY FROM EMPLOYEES;



SELECT COUNT(*)
FROM EMPLOYEES
WHERE SALARY>1000;



SELECT LAST_NAME AS "Nazwisko", FIRST_NAME AS "Imie", HIRE_DATE AS "Ostatnia Data Zatrudnienia"
FROM employees
WHERE ROWNUM <= 1 AND HIRE_DATE = 
(SELECT MAX(HIRE_DATE)
FROM employees
);


SELECT AVG (SALARY) AS "SREDNIA PENSJA",
FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN = '04/11/2004' AND '04/11/2008';

SELECT AVG(SALARY) AS SREDNIE_ZAROBKI FROM EMPLOYEES WHERE HIRE_DATE BETWEEN '04/11/04' AND '07/11/04';

SELECT SUM(MAX_SALARY) FROM JOBS WHERE JOB_ID LIKE 'AD%'; 


