--INSERT INTO COUNTRIES VALUES('PL','POLSKA',1);
--INSERT INTO COUNTRIES 
--VALUES ('SP','HISZPANIA',1);
--INSERT INTO COUNTRIES 
--VALUES('AT','AUSTRIA',1);
--INSERT INTO COUNTRIES 
--VALUES('CL','CZILE',2);


/*INSERT INTO COUNTRIES 
VALUES ('PW','POLSKA',1);
SELECT*FROM COUNTRIES;
*/
--SELECT DISTINCT COUNTRY_NAME FROM COUNTRIES;
--SELECT DISTINCT REGION_ID FROM COUNTRIES;
SELECT EMPLOYEE_ID AS ID_PRACOWNIKA, 
FIRST_NAME AS IMIE, LAST_NAME AS NAZWISKO, 
EMAIL AS ADRES_POCZTOWY,
PHONE_NUMBER AS NUMER_TELEFONU,
HIRE_DATE AS DATA_ZATRUDNIENIA,
JOB_ID AS DZIAL,
SALARY AS PENSJA,
COMMISSION_PCT AS PROWIZJA,
MANAGER_ID AS NR_MENAGERA,
DEPARTMENT_ID AS ID_DZIALU
FROM EMPLOYEES;


SELECT D.EMPLOYEE_ID,D.LAST_NAME,D.PHONE_NUMBER
FROM EMPLOYEES D;
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID IN (101,109);

SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID>100 AND FIRST_NAME LIKE 'De%';
SELECT * FROM EMPLOYEES WHERE LAST_NAME LIKE 'Chen' or last_NAME LIKE '%et';
SELECT * FROM EMPLOYEES WHERE NOT SALARY>5000;
SELECT * FROM EMPLOYEES WHERE LAST_NAME LIKE '_____' AND SALARY<3000;
SELECT * FROM EMPLOYEES WHERE LAST_NAME NOT LIKE '%ki%'
and LAST_NAME NOT LIKE 'Ki%';

SELECT * FROM DEPARTMENTS WHERE DEPARTMENT_ID BETWEEN 50 AND 120;
SELECT * FROM EMPLOYEES WHERE HIRE_DATE BETWEEN '02/02/02' AND '03/12/25';
SELECT * FROM EMPLOYEES WHERE LAST_NAME IN ('Lorentz','Chen');
SELECT * FROM JOBS WHERE JOB_TITLE NOT IN ('Stock Manager','Stock Clerk');


SELECT * FROM JOB_HISTORY ORDER BY 3 DESC; 
SELECT * FROM EMPLOYEES WHERE LAST_NAME NOT LIKE '%ki%'
and LAST_NAME NOT LIKE 'Ki%' ORDER BY LAST_NAME DESC;

SELECT * FROM EMPLOYEES WHERE COMMISSION_PCT IS NOT NULL;

UPDATE EMPLOYEES SET PHONE_NUMBER=444555666 WHERE HIRE_DATE 
BETWEEN '03/06/03' AND '06/12/22';

SELECT * FROM EMPLOYEES WHERE ROWNUM<=5;


DELETE FROM COUNTRIES WHERE COUNTRY_ID IN('KW','PW','ZW','ZM');

DELETE FROM EMPLOYEES WHERE PHONE_NUMBER LIKE '515%' AND FIRST_NAME LIKE 'D%';

DELETE FROM LOCATIONS WHERE STATE_PROVINCE IS NULL;

CREATE TABLE WOJEWODZTWA1 (
ID_WOJEWODZTWA INT,
NAZWA_WOJEWODZTWA VARCHAR (50),
STOLICA_WOJEWODZTWA VARCHAR (50),
POWIERZCHNIA NUMBER(5,5),
ZABYTKI VARCHAR (250)
);

DROP TABLE WOJEWODZTWA;

CREATE TABLE MIASTO (
ID_MIASTO INT NOT NULL,
NAZWA_MIASTA VARCHAR (250) NOT NULL,
POWIERZCHNIA_MIASTA NUMBER(5,5) NOT NULL,
ZABYTKI VARCHAR (250)DEFAULT NULL,
CONSTRAINT PK_MIASTA PRIMARY KEY (ID_DZIELNICY)
);
--DROP TABLE MIASTO;
CREATE TABLE MIASTO (
ID_MIASTO INT NOT NULL,
NAZWA_MIASTA VARCHAR (250) NOT NULL,
POWIERZCHNIA_MIASTA NUMBER(5,5) NOT NULL,
ZABYTKI VARCHAR (250)DEFAULT NULL,
CONSTRAINT PK_MIASTA PRIMARY KEY (ID_MIASTO)
);
ALTER TABLE MIASTO ADD KRAJ VARCHAR (250) NOT NULL;
ALTER TABLE MIASTO ADD WOJEWODZTWO VARCHAR (250) NOT NULL;
--USUWANIE KOLUMN
ALTER TABLE MIASTO DROP COLUMN KRAJ;
ALTER TABLE MIASTO ADD KRAJ VARCHAR (250) NOT NULL;
ALTER TABLE MIASTO DROP(KRAJ, WOJEWODZTWO);
ALTER TABLE MIASTO MODIFY (KRAJ NULL, WOJEWODZTWO NULL);

ALTER TABLE MIASTO MODIFY ID_KRAJ CHAR(2) NULL;
--kluczobcy
ALTER TABLE MIASTO ADD CONSTRAINT FK_KRAJU FOREIGN KEY (ID_KRAJ) 
REFERENCES COUNTRIES (COUNTRY_ID);

--min,max
SELECT MAX(HIRE_DATE)AS OSTATNI_PRACOWNIK FROM EMPLOYEES;
SELECT FIRST_NAME, LAST_NAME,MAX(HIRE_DATE)AS OSTATNI_PRACOWNIK FROM EMPLOYEES GROUP BY FIRST_NAME, LAST_NAME ORDER BY OSTATNI_PRACOWNIK DESC;

--LICZBA PRACOWNIKÓW
SELECT COUNT (EMPLOYEE_ID) AS LICZBA_PRACOWNIKOW FROM EMPLOYEES;
SELECT COUNT (EMPLOYEE_ID) AS LICZBA_PRACOWNIKOW FROM EMPLOYEES WHERE SALARY>10000;

SELECT ROUND(AVG(SALARY),2) AS SREDNIE_ZAROBKI FROM EMPLOYEES WHERE HIRE_DATE BETWEEN '04/11/04' AND '07/11/04'; 
SELECT SUM(MAX_SALARY) FROM JOBS WHERE JOB_ID LIKE 'AD%'; 
