--INSERT INTO COUNTRIES VALUES('PL','POLSKA',1);
--INSERT INTO COUNTRIES 
--VALUES ('SP','HISZPANIA',1);
--INSERT INTO COUNTRIES 
--VALUES('AT','AUSTRIA',1);
--INSERT INTO COUNTRIES 
--VALUES('CL','CZILE',2);


/*INSERT INTO COUNTRIES 
VALUES ('PW','POLSKA',1);
SELECT*FROM COUNTRIES;
*/
--SELECT DISTINCT COUNTRY_NAME FROM COUNTRIES;
--SELECT DISTINCT REGION_ID FROM COUNTRIES;
SELECT EMPLOYEE_ID AS ID_PRACOWNIKA, 
FIRST_NAME AS IMIE, LAST_NAME AS NAZWISKO, 
EMAIL AS ADRES_POCZTOWY,
PHONE_NUMBER AS NUMER_TELEFONU,
HIRE_DATE AS DATA_ZATRUDNIENIA,
JOB_ID AS DZIAL,
SALARY AS PENSJA,
COMMISSION_PCT AS PROWIZJA,
MANAGER_ID AS NR_MENAGERA,
DEPARTMENT_ID AS ID_DZIALU
FROM EMPLOYEES;


SELECT D.EMPLOYEE_ID,D.LAST_NAME,D.PHONE_NUMBER
FROM EMPLOYEES D;
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID IN (101,109);







